version: '3.9'
services:
  app:
    build: .
    image: saifuddin1703/bookzone
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URL_PROD='mongodb+srv://saifuddin:6oF978zGdCLiZNBU@cluster0.uc7oy8l.mongodb.net/?retryWrites=true&w=majority'
      - MONGODB_URL_TEST='mongodb://127.0.0.1:27017/booksDB'
      - JWT_SECRET='VERY VERY SECRET'
      - EMAIL='monkeycoder144@gmail.com'
      - PASSWORD='bhqatfflajlbcfrk'
      - OAUTH_CLIENTID='348352542860-22k3g090m4eelreime7c6v4737a52irr.apps.googleusercontent.com'
      - OAUTH_CLIENT_SECRET='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'
      - OAUTH_REFRESH_TOKEN='1//04-ghyqs7S6wdCgYIARAAGAQSNwF-L9IrOy33Aiuoid_EqSjDEgLZZNFH5HGYPGnlB0IrBZDjn2EvPbL9OLq6FSXWxKxgofET4Y8'

